### ISSUE TITLE
Add Firefox OS support

### ISSUE THREAD

**Issue by kirchner** [aforemny/magic#1]
Add a manifest file, package the whole app into a zip-file and create a mini-manifest file.  This should be straight forward.  A description of the process can be found at https://developer.mozilla.org/en-US/Marketplace/Options/Self_publishing#Self-publishing_packaged_apps.

**Comment by aforemny** [comment]
Merged in 7a7b1df60036fadd4042f52c3f43db624bc21a00. Thanks!
